version: '3.5'

services:
  database:
    container_name: database_news
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/pgdata
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news
    ports:
      - '5432:5432'
